#!/usr/bin/bash

addr=$1 # Example: 12,34,56

./WREN
sleep 0.1
./debug_analyse.py RWb:422181b0=0 # NSS pin low
./debug_analyse.py RWb:4000380C=D7 # Sector ERASE
./debug_analyse.py RWb:4000380C=$addr
./debug_analyse.py RWb:422181b0=1 # NSS pin high


