#!/usr/bin/bash

./debug_analyse.py RWb:422181b0=0 # NSS pin low
./debug_analyse.py RWb:4000380C=9F
./debug_analyse.py RWb:4000380C=0*3 # For read result
./debug_analyse.py RWb:422181b0=1 # NSS pin high


