#!/usr/bin/bash

./debug_analyse.py RWb:422181b0=0 # NSS pin low
./debug_analyse.py RWb:4000380C=AB
./debug_analyse.py RWb:4000380C=0*6 # For 3 dummy bytes and read 3 bytes of result
./debug_analyse.py RWb:422181b0=1 # NSS pin high


