#!/usr/bin/bash

./debug_analyse.py RWb:422181b0=0 # NSS pin low
./debug_analyse.py RWb:4000380C=5 # RDSR
./debug_analyse.py RWb:4000380C=0 # For read result
./debug_analyse.py RWb:422181b0=1 # NSS pin high


