#!/usr/bin/bash

addr=$1
count=$2

./debug_analyse.py RWb:422181b0=0 
./debug_analyse.py RWb:4000380C=3
./debug_analyse.py RWb:4000380C=$addr
./debug_analyse.py RWb:4000380C=0*$count
./debug_analyse.py RWb:422181b0=1
