#!/usr/bin/bash

./debug_analyse.py RWb:422181b0=0 # NSS pin low
./debug_analyse.py RWb:4000380C=1
./debug_analyse.py RWb:4000380C=$1 # For write value
./debug_analyse.py RWb:422181b0=1 # NSS pin high


